convert kubernetes secrets (stringData) to .env file

diff --git a/k8s-secrets-to-env b/k8s-secrets-to-env
--- a/k8s-secrets-to-env
+++ b/k8s-secrets-to-env
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
-RUN_SOURCE=${1}
+SECRETS_FILE=${1}
+RUN_SOURCE=${2}
+
+INPUT_EXAMPLE="k8s-secrets-to-env <path/to/secrets>"
+
+if test -z $SECRETS_FILE
+then
+    echo "PATH TO SECRETS FILE IS MISSING [$INPUT_EXAMPLE]"
+    exit 1;
+fi
+
+mkdir -p ".generated/"
 
 export RAND_TMP_ID="r_$(date +%Y%m%d%H%M%S)_$(( ( RANDOM % 10 )  + 1 ))"
-sed -e '1,/stringData:/d;s/:[^:\/\/]/=/g;s/$//g;s/ *=/=/g;s/^[ \t]*//;s/[^=]\+/export &; &/;' secrets.yaml > .generated/$RAND_TMP_ID.env
+sed -e '1,/stringData:/d;s/:[^:\/\/]/=/g;s/$//g;s/ *=/=/g;s/^[ \t]*//;s/[^=]\+/export &; &/;' $SECRETS_FILE > .generated/$RAND_TMP_ID.env
 
 set -a
 source .generated/$RAND_TMP_ID.env
